### ISSUE TITLE
White divider line with dark theme 

### ISSUE THREAD

**Issue by mikejones3** [flagrow/ads#14]
Using the dark theme in Flarum within post ads creates an issue with the dividers for the ad. The bottom divider line is correctly dark but the divider line above the add is white:

![ads](https://user-images.githubusercontent.com/13171497/40365689-06d27fe4-5d8a-11e8-8e9e-dcfa1792fa74.PNG)

**Comment by luceos** [comment]
Have you been able to change the color by using some custom less?

**Comment by mikejones3** [comment]
> Have you been able to change the color by using some custom less?

Assuming you mean CSS? I have not tried yet but will look into it. Either way probably should be able to know when you are using a dark theme no?

**Comment by mikejones3** [comment]
I just played with the developer's console in chrome, maybe I am just not familiar with the Flarum CSS but I was having issues finding these "dividers" while looking through the css

**Comment by luceos** [comment]
I'll take a look when we do a full refactor of the extension 👍
