### ISSUE TITLE
Left Column Layout issue

### ISSUE THREAD

**Issue by acseven** [flagrow/ads#4]
Hi,
I'm testing the plugin on a flarum board and I'm getting this inconsistency when using an adsense responsive html block inside "_Ad position in the left column under tags on frontpage_":

![scrn](https://cloud.githubusercontent.com/assets/1176371/24323073/1913ca9c-1168-11e7-91bd-ba19924e1e81.png)

It's appearing partially under the discussions list.

**Comment by luceos** [comment]
You can format the Ad however you like it has a unique id. Feel free to add a LESS snippet in your admin area to target that specific element.
